import type { Client, Worker, Task } from "@/types"

export const sampleClients: Client[] = [
  {
    id: "client-1",
    name: "TechCorp Solutions",
    email: "contact@techcorp.com",
    priority: "high",
    budget: 50000,
    location: "San Francisco, CA",
    industry: "Technology",
    requirements: ["React", "Node.js", "AWS"],
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "client-2",
    name: "Design Studio Pro",
    email: "hello@designstudio.com",
    priority: "medium",
    budget: 25000,
    location: "New York, NY",
    industry: "Design",
    requirements: ["UI/UX", "Figma", "Branding"],
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "client-3",
    name: "FinanceFlow Inc",
    email: "info@financeflow.com",
    priority: "high",
    budget: 75000,
    location: "Chicago, IL",
    industry: "Finance",
    requirements: ["Python", "Data Analysis", "Security"],
    createdAt: new Date("2024-01-20"),
  },
]

export const sampleWorkers: Worker[] = [
  {
    id: "worker-1",
    name: "Sarah Chen",
    email: "sarah.chen@email.com",
    skills: ["React", "TypeScript", "Node.js", "AWS"],
    hourlyRate: 85,
    availability: "available",
    location: "San Francisco, CA",
    experience: 5,
    rating: 4.8,
    specializations: ["Frontend Development", "Cloud Architecture"],
    maxHoursPerWeek: 40,
  },
  {
    id: "worker-2",
    name: "Marcus Johnson",
    email: "marcus.j@email.com",
    skills: ["UI/UX", "Figma", "Adobe Creative Suite", "Prototyping"],
    hourlyRate: 75,
    availability: "available",
    location: "New York, NY",
    experience: 7,
    rating: 4.9,
    specializations: ["User Experience", "Visual Design"],
    maxHoursPerWeek: 35,
  },
  {
    id: "worker-3",
    name: "Elena Rodriguez",
    email: "elena.r@email.com",
    skills: ["Python", "Data Science", "Machine Learning", "SQL"],
    hourlyRate: 95,
    availability: "busy",
    location: "Austin, TX",
    experience: 8,
    rating: 4.7,
    specializations: ["Data Analysis", "AI/ML"],
    maxHoursPerWeek: 30,
  },
]

export const sampleTasks: Task[] = [
  {
    id: "task-1",
    title: "E-commerce Platform Development",
    description: "Build a modern e-commerce platform with React and Node.js",
    clientId: "client-1",
    requiredSkills: ["React", "Node.js", "PostgreSQL"],
    estimatedHours: 120,
    deadline: new Date("2024-04-15"),
    priority: "high",
    status: "pending",
    budget: 15000,
    complexity: "complex",
  },
  {
    id: "task-2",
    title: "Brand Identity Design",
    description: "Create complete brand identity including logo, colors, and guidelines",
    clientId: "client-2",
    requiredSkills: ["Branding", "Figma", "Illustration"],
    estimatedHours: 60,
    deadline: new Date("2024-03-30"),
    priority: "medium",
    status: "pending",
    budget: 8000,
    complexity: "medium",
  },
  {
    id: "task-3",
    title: "Financial Data Analysis Dashboard",
    description: "Build analytics dashboard for financial data visualization",
    clientId: "client-3",
    requiredSkills: ["Python", "Data Visualization", "SQL"],
    estimatedHours: 80,
    deadline: new Date("2024-04-01"),
    priority: "urgent",
    status: "pending",
    budget: 12000,
    complexity: "complex",
  },
]
